version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

project_name: katana

builds:
  - id: katana
    ldflags:
      - -s -w
    binary: katana
    main: ./cmd/katana/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64

archives:
  - formats: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"

announce:
  slack:
    enabled: true
    channel: '#release'
    username: GoReleaser
    message_template: 'New Release: {{ .ProjectName }} {{.Tag}} is published! Check it out at {{ .ReleaseURL }}'
  discord:
    enabled: true
    message_template: '**New Release: {{ .ProjectName }} {{.Tag}}** is published! Check it out at {{ .ReleaseURL }}'
