// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EndpointsColumns holds the columns for the "endpoints" table.
	EndpointsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString},
		{Name: "method", Type: field.TypeString},
		{Name: "body", Type: field.TypeString},
		{Name: "headers", Type: field.TypeJSON},
		{Name: "source", Type: field.TypeString},
	}
	// EndpointsTable holds the schema information for the "endpoints" table.
	EndpointsTable = &schema.Table{
		Name:       "endpoints",
		Columns:    EndpointsColumns,
		PrimaryKey: []*schema.Column{EndpointsColumns[0]},
	}
	// EndpointLinksColumns holds the columns for the "endpoint_links" table.
	EndpointLinksColumns = []*schema.Column{
		{Name: "endpoint_id", Type: field.TypeInt},
		{Name: "link_id", Type: field.TypeInt},
	}
	// EndpointLinksTable holds the schema information for the "endpoint_links" table.
	EndpointLinksTable = &schema.Table{
		Name:       "endpoint_links",
		Columns:    EndpointLinksColumns,
		PrimaryKey: []*schema.Column{EndpointLinksColumns[0], EndpointLinksColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "endpoint_links_endpoint_id",
				Columns:    []*schema.Column{EndpointLinksColumns[0]},
				RefColumns: []*schema.Column{EndpointsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "endpoint_links_link_id",
				Columns:    []*schema.Column{EndpointLinksColumns[1]},
				RefColumns: []*schema.Column{EndpointsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EndpointsTable,
		EndpointLinksTable,
	}
)

func init() {
	EndpointLinksTable.ForeignKeys[0].RefTable = EndpointsTable
	EndpointLinksTable.ForeignKeys[1].RefTable = EndpointsTable
}
