// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/projectdiscovery/katana/ent/endpoint"
	"github.com/projectdiscovery/katana/ent/predicate"
)

// EndpointUpdate is the builder for updating Endpoint entities.
type EndpointUpdate struct {
	config
	hooks    []Hook
	mutation *EndpointMutation
}

// Where appends a list predicates to the EndpointUpdate builder.
func (eu *EndpointUpdate) Where(ps ...predicate.Endpoint) *EndpointUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetURL sets the "url" field.
func (eu *EndpointUpdate) SetURL(s string) *EndpointUpdate {
	eu.mutation.SetURL(s)
	return eu
}

// SetMethod sets the "method" field.
func (eu *EndpointUpdate) SetMethod(s string) *EndpointUpdate {
	eu.mutation.SetMethod(s)
	return eu
}

// SetBody sets the "body" field.
func (eu *EndpointUpdate) SetBody(s string) *EndpointUpdate {
	eu.mutation.SetBody(s)
	return eu
}

// SetHeaders sets the "headers" field.
func (eu *EndpointUpdate) SetHeaders(m map[string]string) *EndpointUpdate {
	eu.mutation.SetHeaders(m)
	return eu
}

// SetSource sets the "source" field.
func (eu *EndpointUpdate) SetSource(s string) *EndpointUpdate {
	eu.mutation.SetSource(s)
	return eu
}

// AddLinkIDs adds the "links" edge to the Endpoint entity by IDs.
func (eu *EndpointUpdate) AddLinkIDs(ids ...int) *EndpointUpdate {
	eu.mutation.AddLinkIDs(ids...)
	return eu
}

// AddLinks adds the "links" edges to the Endpoint entity.
func (eu *EndpointUpdate) AddLinks(e ...*Endpoint) *EndpointUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return eu.AddLinkIDs(ids...)
}

// Mutation returns the EndpointMutation object of the builder.
func (eu *EndpointUpdate) Mutation() *EndpointMutation {
	return eu.mutation
}

// ClearLinks clears all "links" edges to the Endpoint entity.
func (eu *EndpointUpdate) ClearLinks() *EndpointUpdate {
	eu.mutation.ClearLinks()
	return eu
}

// RemoveLinkIDs removes the "links" edge to Endpoint entities by IDs.
func (eu *EndpointUpdate) RemoveLinkIDs(ids ...int) *EndpointUpdate {
	eu.mutation.RemoveLinkIDs(ids...)
	return eu
}

// RemoveLinks removes "links" edges to Endpoint entities.
func (eu *EndpointUpdate) RemoveLinks(e ...*Endpoint) *EndpointUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return eu.RemoveLinkIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EndpointUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(eu.hooks) == 0 {
		if err = eu.check(); err != nil {
			return 0, err
		}
		affected, err = eu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EndpointMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = eu.check(); err != nil {
				return 0, err
			}
			eu.mutation = mutation
			affected, err = eu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eu.hooks) - 1; i >= 0; i-- {
			if eu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = eu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EndpointUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EndpointUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EndpointUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EndpointUpdate) check() error {
	if v, ok := eu.mutation.URL(); ok {
		if err := endpoint.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Endpoint.url": %w`, err)}
		}
	}
	if v, ok := eu.mutation.Method(); ok {
		if err := endpoint.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Endpoint.method": %w`, err)}
		}
	}
	return nil
}

func (eu *EndpointUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   endpoint.Table,
			Columns: endpoint.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: endpoint.FieldID,
			},
		},
	}
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.URL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: endpoint.FieldURL,
		})
	}
	if value, ok := eu.mutation.Method(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: endpoint.FieldMethod,
		})
	}
	if value, ok := eu.mutation.Body(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: endpoint.FieldBody,
		})
	}
	if value, ok := eu.mutation.Headers(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: endpoint.FieldHeaders,
		})
	}
	if value, ok := eu.mutation.Source(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: endpoint.FieldSource,
		})
	}
	if eu.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   endpoint.LinksTable,
			Columns: endpoint.LinksPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: endpoint.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.RemovedLinksIDs(); len(nodes) > 0 && !eu.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   endpoint.LinksTable,
			Columns: endpoint.LinksPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: endpoint.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   endpoint.LinksTable,
			Columns: endpoint.LinksPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: endpoint.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{endpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// EndpointUpdateOne is the builder for updating a single Endpoint entity.
type EndpointUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EndpointMutation
}

// SetURL sets the "url" field.
func (euo *EndpointUpdateOne) SetURL(s string) *EndpointUpdateOne {
	euo.mutation.SetURL(s)
	return euo
}

// SetMethod sets the "method" field.
func (euo *EndpointUpdateOne) SetMethod(s string) *EndpointUpdateOne {
	euo.mutation.SetMethod(s)
	return euo
}

// SetBody sets the "body" field.
func (euo *EndpointUpdateOne) SetBody(s string) *EndpointUpdateOne {
	euo.mutation.SetBody(s)
	return euo
}

// SetHeaders sets the "headers" field.
func (euo *EndpointUpdateOne) SetHeaders(m map[string]string) *EndpointUpdateOne {
	euo.mutation.SetHeaders(m)
	return euo
}

// SetSource sets the "source" field.
func (euo *EndpointUpdateOne) SetSource(s string) *EndpointUpdateOne {
	euo.mutation.SetSource(s)
	return euo
}

// AddLinkIDs adds the "links" edge to the Endpoint entity by IDs.
func (euo *EndpointUpdateOne) AddLinkIDs(ids ...int) *EndpointUpdateOne {
	euo.mutation.AddLinkIDs(ids...)
	return euo
}

// AddLinks adds the "links" edges to the Endpoint entity.
func (euo *EndpointUpdateOne) AddLinks(e ...*Endpoint) *EndpointUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return euo.AddLinkIDs(ids...)
}

// Mutation returns the EndpointMutation object of the builder.
func (euo *EndpointUpdateOne) Mutation() *EndpointMutation {
	return euo.mutation
}

// ClearLinks clears all "links" edges to the Endpoint entity.
func (euo *EndpointUpdateOne) ClearLinks() *EndpointUpdateOne {
	euo.mutation.ClearLinks()
	return euo
}

// RemoveLinkIDs removes the "links" edge to Endpoint entities by IDs.
func (euo *EndpointUpdateOne) RemoveLinkIDs(ids ...int) *EndpointUpdateOne {
	euo.mutation.RemoveLinkIDs(ids...)
	return euo
}

// RemoveLinks removes "links" edges to Endpoint entities.
func (euo *EndpointUpdateOne) RemoveLinks(e ...*Endpoint) *EndpointUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return euo.RemoveLinkIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EndpointUpdateOne) Select(field string, fields ...string) *EndpointUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Endpoint entity.
func (euo *EndpointUpdateOne) Save(ctx context.Context) (*Endpoint, error) {
	var (
		err  error
		node *Endpoint
	)
	if len(euo.hooks) == 0 {
		if err = euo.check(); err != nil {
			return nil, err
		}
		node, err = euo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EndpointMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = euo.check(); err != nil {
				return nil, err
			}
			euo.mutation = mutation
			node, err = euo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(euo.hooks) - 1; i >= 0; i-- {
			if euo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = euo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, euo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EndpointUpdateOne) SaveX(ctx context.Context) *Endpoint {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EndpointUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EndpointUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EndpointUpdateOne) check() error {
	if v, ok := euo.mutation.URL(); ok {
		if err := endpoint.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Endpoint.url": %w`, err)}
		}
	}
	if v, ok := euo.mutation.Method(); ok {
		if err := endpoint.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Endpoint.method": %w`, err)}
		}
	}
	return nil
}

func (euo *EndpointUpdateOne) sqlSave(ctx context.Context) (_node *Endpoint, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   endpoint.Table,
			Columns: endpoint.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: endpoint.FieldID,
			},
		},
	}
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Endpoint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, endpoint.FieldID)
		for _, f := range fields {
			if !endpoint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != endpoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.URL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: endpoint.FieldURL,
		})
	}
	if value, ok := euo.mutation.Method(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: endpoint.FieldMethod,
		})
	}
	if value, ok := euo.mutation.Body(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: endpoint.FieldBody,
		})
	}
	if value, ok := euo.mutation.Headers(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: endpoint.FieldHeaders,
		})
	}
	if value, ok := euo.mutation.Source(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: endpoint.FieldSource,
		})
	}
	if euo.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   endpoint.LinksTable,
			Columns: endpoint.LinksPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: endpoint.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.RemovedLinksIDs(); len(nodes) > 0 && !euo.mutation.LinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   endpoint.LinksTable,
			Columns: endpoint.LinksPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: endpoint.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.LinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   endpoint.LinksTable,
			Columns: endpoint.LinksPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: endpoint.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Endpoint{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{endpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
