// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/projectdiscovery/katana/ent/endpoint"
	"github.com/projectdiscovery/katana/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	endpointFields := schema.Endpoint{}.Fields()
	_ = endpointFields
	// endpointDescURL is the schema descriptor for url field.
	endpointDescURL := endpointFields[0].Descriptor()
	// endpoint.URLValidator is a validator for the "url" field. It is called by the builders before save.
	endpoint.URLValidator = endpointDescURL.Validators[0].(func(string) error)
	// endpointDescMethod is the schema descriptor for method field.
	endpointDescMethod := endpointFields[1].Descriptor()
	// endpoint.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	endpoint.MethodValidator = endpointDescMethod.Validators[0].(func(string) error)
}
