name: 🔨 Release Test

on:
  pull_request:
    paths:
      - "**.yml"
      - "**.go"
      - "**.mod"
  workflow_dispatch:

jobs:
  release-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: projectdiscovery/actions/setup/go@v1

      - name: release test
        uses: projectdiscovery/actions/goreleaser@v1
        with:
          args: --snapshot --clean
          workdir: .
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
